---
openapi: "3.0"
info:
  title: Generated API
  version: "1.0"
paths:
  /generated:
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Model'
components:
  schemas:
    Model:
      type: object
      properties:
        name:
          type: string
