package com.example.demo;

import javax.servlet.ServletContext;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import io.swagger.jaxrs.config.SwaggerContextService;
import io.swagger.models.Contact;
import io.swagger.models.Info;
import io.swagger.models.License;
import io.swagger.models.Swagger;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Bean
	CommandLineRunner bootstrap() {
		return args -> {
			Info info = new Info()
					.title("OpenAPI Server")
					.description(
							"No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)")
					.termsOfService("")
					.contact(new Contact()
							.email(""))
					.license(new License()
							.name("")
							.url("http://unlicense.org"));

			Swagger swagger = new Swagger().info(info);
			swagger.setSwagger("3.0");

			new SwaggerContextService().withConfigId("default").updateSwagger(swagger);
		};
	}

}